### ISSUE TITLE
Add first release of requirements.

### ISSUE THREAD

**Issue by ghost** [muuvy/docs#1]
Since the course has been designed to use completely different technologies, we need tro adapt the requirements specification slightly.

**Comment by ghost** [comment]
Added document to task, since push to server repository does not work: [Aufgabestellung_Vertiefungsarbeit_MovieWorld-SE.pdf](https://github.com/muuvy/docs/files/3206599/Aufgabestellung_Vertiefungsarbeit_MovieWorld-SE.pdf)

**Comment by lucahost** [comment]
This issue can be resolved. 
As of last week all members of muuvy have r/w access to all repos.
Requirements doc is saved under /docs/requirements
